### ISSUE TITLE
Too much steez

### ISSUE THREAD

**Issue by ajwhite** [Rican7/facebook-birthday-thanks#2]
![](http://www.quickmeme.com/img/21/2166bddb485fc4c8fd6e7b5e44de52f3d5923509b43c1656c6588129eacaef84.jpg)

Happy birthday dude, maybe a REAL PERSON will respond to this! :trollface: :smile: :balloon: :cake: :fireworks: 

LGTM :+1:

**Comment by Rican7** [comment]
Haha. You're a boss. Thanks a lot, man.

**Comment by ajwhite** [comment]
This shall suffice
